jeevan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url('^', include('visit.urls')),     #  adding url path for vist application
    url('^', include('main.urls')),     #  adding url path for main application

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.conf.urls import url
from . import views

app_name = 'main'

urlpatterns = [
    url(r'^home/', views.index, name='index'),    # Home page
    url(r'e-market/$', views.emarket, name = 'emarket'),     # rain water 
    url(r'e-market/add-eShop/$', views.AddShop.as_view(), name = 'add-shop'),   # Add an E shop
    url(r'incubators/(?P<incubator_id>[0-9]+)/', views.details, name = 'details'),
    url(r'location/', views.location, name = 'location'),           #  map
    url(r'added/', views.added, name = 'added'),      #your incubator will be added soon page
    url(r'results', views.result, name = 'result'),         # For search function
    url(r'water-footprint/$', views.footprint, name = 'footprint'),
    url(r'underground-water-data/$', views.data, name = 'data'),    # ground water data from ISRO
    url(r'join-movement/$', views.join, name = 'join'),           #for the societies.
    url(r'add-movement/', views.Add.as_view(), name = 'add'),
    url(r'discover/$', views.discover, name = 'discover'),
    url(r'discover/(?P<discover_id>[0-9]+)', views.disc_details, name = 'disc-details'),    # 
    url(r'add-discover/$', views.AddDiscover.as_view(), name = 'add-discover'),
    url(r'contact/$', views.ContactForm.as_view(), name = 'contact-form'),

]

    

visit/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from .views import *
app_name = 'visit'

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'login/', auth_views.LoginView.as_view(), {'template_name': 'visit/registration/login.html'}, name='login'),
    url(r'register/', views.Registration, name='registration'),
    url(r'profile/$', views.Profile, name='profile'),
    url(r'^logout/', views.logoutRequest, name='logout'),
   # url(r'^profiles/new/(?P<pk>\d+)/$', NewUserProfileView.as_view(), name="new-user-profile"),
  #  url(r'^users/(?P<pk>\d+)/edit/', EditUserProfileView.as_view(), name="edit-user-profile"),

]

visit/models.py
import uuid
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser



class UserProfile(models.Model):
    GENDER_CHOICES = (
        ('Male', 'Male'),
        ('Female', 'Female'),
    )
    USER_TYPE = (
        ('Entrepreneur', 'Entrepreneur'),
        ('Mentor', 'Mentor'),
        ('Investor', 'Investor'),
        ('Job seeker', 'Job Seeker'),
    )

    user = models.OneToOneField(User, on_delete = models.CASCADE)
    birth_date=models.DateField(default= None, null = True)
    gender = models.CharField(max_length=20, choices=GENDER_CHOICES)
    address = models.CharField(max_length=150)
    locality = models.CharField(max_length=30)
    state = models.CharField(max_length=30, default='Enter State')
    postal_code_4 = models.PositiveIntegerField(null=True)
    user_type = models.CharField(max_length=20, choices=USER_TYPE)
    activation_key = models.CharField(max_length=64, verbose_name=u"Activation key",default=uuid.uuid1())
    is_verified = models.BooleanField(default=False)
    profile_photo = models.FileField(default = None, null = True)
    cover_photo = models.FileField(default=None, null=True)

    def __unicode__(self):
        return u"%s" % self.user

def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(create_user_profile, sender=User)

visit/forms.py
from django import forms
from . import  models
from .models import *
from django.contrib.auth.models import User   # fill in custom user info then save it



class UserRegistrationForm(forms.Form):
    username = forms.CharField(required=True)
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    password = forms.CharField(widget=forms.PasswordInput)



    class Meta:
        model = User
        fields = ['username','first_name','last_name', 'email', 'password']


class LoginForm(forms.Form):
    email = forms.EmailField(required=True)
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('birth_date', 'state', 'gender', 'address') #Note that we didn't mention user field here.

    def save(self, user=None):
        user_profile = super(UserProfileForm, self).save(commit=False)
        if user:
            user_profile.user = user
        user_profile.save()
        return user_profile

visit/views.py
from django.shortcuts import render
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django import forms
from django.shortcuts import render
from visit.models import *
from .forms import UserRegistrationForm, LoginForm
from django.urls import reverse

def Registration(request):
    if request.user.is_authenticated:
        return render(request, 'visit/registration/register.html')
    if request.method == 'POST':
        form  = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = User.objects.create_user(username = form.cleaned_data['username'],email = form.cleaned_data['email'] , password = form.cleaned_data['password'])
            user.save()

            return HttpResponseRedirect('/')
        else:
            return render(request, 'visit/registration/register.html', {'form': form},)

    else:
        form= UserRegistrationForm()
        context = {'form': form}
        return render(request, 'visit/registration/register.html', context )


@login_required
def Profile(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect('/login/')
    return render(request,'visit/profile.html')

def LoginRequest(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/home/')
    if request.method == 'POST':
        form  = LoginRequest(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            UserProfile = authenticate(username=username, password=password)
            if UserProfile is not None:
                login(request, UserProfile)
                return HttpResponseRedirect('/home/')
            else:
                return render(request,'visit/registration/login.html',{'form':form})
        else:
            return render(request, 'visit/registration/login.html', {'form': form})

    else:
        form= LoginForm()
        context = {'form': form}
        return render(request, 'visit/registration/login.html', context, )


def logoutRequest(request):
    logout(request)
    return  render(request, 'visit/index.html')



def index(request):
    return render(request, 'visit/index.html', context = None)

visit/templates/visit/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load staticfiles %}
  <meta charset="utf-8">
  <title>Jeevan</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">

<style>
  
</style>  

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900" rel="stylesheet">

  <!-- Bootstrap CSS File -->
  <link href="{% static "visit/lib/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">

  <!-- Libraries CSS Files -->
  <link href="{% static "visit/lib/font-awesome/css/font-awesome.min.css"%}" rel="stylesheet">
  <link href="{% static "visit/lib/owlcarousel/owl.carousel.min.css" %}" rel="stylesheet">
  <link href="{% static "visit/lib/owlcarousel/owl.theme.min.css"%}" rel="stylesheet">
  <link href="{% static "visit/lib/owlcarousel/owl.transitions.min.css" %}" rel="stylesheet">

  <!-- Main Stylesheet File -->
  <link href="{%static "visit/css/style.css"%}" rel="stylesheet">

  <!--Your custom colour override - predefined colours are: colour-blue.css, colour-green.css, colour-lavander.css, orange is default-->
  <link href="#" id="colour-blue" rel="stylesheet">

</head>

<body class="page-index has-hero">
  <!--Change the background class to alter background image, options are: benches, boots, buildings, city, metro -->
  <div id="background-wrapper" class="city" data-stellar-background-ratio="0.1">

    <!-- ======== @Region: #navigation ======== -->


    <div id="navigation" class="wrapper">
      <!--Hidden Header Region-->
      <div class="header-hidden collapse">
        <div class="header-hidden-inner container">
          <div class="row">
            <div class="col-md-3">
              <h3>
                  About Us
                </h3>
              <p>Jeevan is dedicated to preserving Groundwater level and fighting Day Zero.</p>
              <a href="about.html" class="btn btn-more"><i class="fa fa-plus"></i> Learn more</a>
            </div>
            <div class="col-md-3">
              <!--@todo: replace with company contact details-->
              <h3>
                  Contact Us
                </h3>
              <address>
                  <strong>Jeevan</strong>
                  <abbr title="Address"><i class="fa fa-pushpin"></i></abbr>
                  MMMDU, Mullana, Ambala- Haryana
                  <br>
                  <abbr title="Phone"><i class="fa fa-phone"></i></abbr>
                  8219984448
                  <br>
                  <abbr title="Email"><i class="fa fa-envelope-alt"></i></abbr>
                  info@Jeevan.com
                </address>
            </div>
            <div class="col-md-6">
              <!--Colour & Background Switch for demo - @todo: remove in production-->
              <h3>
                  Theme Variations
                </h3>
              <div class="switcher">
                <div class="cols">
                  Backgrounds:
                  <br>
                  <a href="#benches" class="background benches active" title="Benches">Benches</a> <a href="#boots" class="background boots " title="Boots">Boots</a> <a href="#buildings" class="background buildings " title="Buildings">Buildings</a>
                  <a
                    href="#city" class="background city " title="City">City</a> <a href="#metro" class="background metro " title="Metro">Metro</a>
                </div>
                <div class="cols">
                  Colours:
                  <br>
                  <a href="#orange" class="colour orange active" title="Orange">Orange</a> <a href="#green" class="colour green " title="Green">Green</a> <a href="#blue" class="colour blue " title="Blue">Blue</a> <a href="#lavender" class="colour lavender "
                    title="Lavender">Lavender</a>
                </div>
              </div>
              <p>
                <small>Selection is not persistent.</small>
              </p>
            </div>
          </div>
        </div>
      </div>
      <!--Header & navbar-branding region-->
      <div class="header">
        <div class="header-inner container">
          <div class="row">
            <div class="col-md-8">
              <!--navbar-branding/logo - hidden image tag & site name so things like Facebook to pick up, actual logo set via CSS for flexibility -->
              <a class="navbar-brand" title="Home" href = "{% url "visit:index"%}">
                <h1 class="hidden">
                    <h1>Jeevan</h1>
                  </h1>
              </a>
			  <br/>
              <div class="navbar-slogan">
                 Every Drop Counts
                <br> By Team Infinity
              </div>
            </div>
            <!--header rightside-->
            <div class="col-md-4">
              <!--user menu-->
              <ul class="list-inline user-menu pull-right">
              </ul>
              <ul class="list-inline user-menu pull-right">
                <li class="user-register"><i class="fa fa-edit text-primary "></i> <a href="{% url 'visit:registration' %}" class="text-uppercase">Register</a></li>
                <li class="user-login"><i class="fa fa-sign-in text-primary"></i> <a href="{% url 'visit:login' %}" class="text-uppercase">Login</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="container">
        <div class="navbar navbar-default">
          <!--mobile collapse menu button-->
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>

          <!--everything within this div is collapsed on mobile-->
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav" id="main-menu">
              <li class="icon-link">
                <a href="{%url "visit:index"%}"><i class="fa fa-home"></i></a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Comunity</a>
                <!-- Dropdown Menu -->
                <ul class="dropdown-menu">
                  <li class="dropdown-header"> </li>
                  <li><a href="elements.html" tabindex="-1" class="menu-item">Services</a></li>
                  <li><a href="about.html" tabindex="-1" class="menu-item">About Us</a></li>
                  <li><a href="login.html" tabindex="-1" class="menu-item">Login</a></li>
                  <li><a href="register.html" tabindex="-1" class="menu-item">Sign-Up</a></li>
                  <li class="dropdown-footer">Connect</li>
                </ul>
              </li>
              <li><a href="{%url "visit:registration" %}">Join Us</a></li>
              <li class="dropdown dropdown-mm">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">About
                  </a>
                <!-- Dropdown Menu -->
                <ul class="dropdown-menu dropdown-menu-mm dropdown-menu-persist">
                  <li class="row">
                    <ul class="col-md-6">
                      <li class="dropdown-header">Websites and Apps</li>
                      <li><a href="#">Analysis and Planning</a></li>
                      <li><a href="#">User Experience / Information Architecture</a></li>
                      <li><a href="#">User Interface Design / UI Design</a></li>
                      <li><a href="#">Code &amp; Development / Implementation &amp; Support</a></li>
                    </ul>
                    <ul class="col-md-6">
                      <li class="dropdown-header">Enterprise solutions</li>
                      <li><a href="#">Business Analysis</a></li>
                      <li><a href="#">Custom UX Consulting</a></li>
                      <li><a href="#">Quality Assurance</a></li>
                    </ul>
                  </li>
                  <li class="dropdown-footer">
                    <div class="row">
                      <div class="col-md-7">Like the lite version? <strong>Get the extended version of Flexor.</strong></div>
                      <div class="col-md-5">
                        <a href="https://bootstrapmade.com" class="btn btn-more btn-lg pull-right"><i class="fa fa-cloud-download"></i> Get It Now</a>
                      </div>
                    </div>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
          <!--/.navbar-collapse -->
        </div>
      </div>
    </div>
    <div class="hero" id="highlighted">
      <div class="inner">
        <!--Slideshow-->
        <div id="highlighted-slider" class="container">
          <div class="item-slider" data-toggle="owlcarousel" data-owlcarousel-settings='{"singleItem":true, "navigation":true, "transitionStyle":"fadeUp"}'>
            <!--Slideshow content-->
            <!--Slide 1-->

{%block content%}
{%endblock%}

</div>
                <div class="col-md-6 hidden-xs">
                  <img src="img/slides/slide2.png" alt="Slide 2" class="center-block img-responsive">
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <footer id="footer" class="block block-bg-grey-dark" data-block-bg-img="img/bg_footer-map.png" data-stellar-background-ratio="0.4">
    <div class="container">

      <div class="row" id="contact">

        <div class="col-md-3">
          <address>
              <strong>JunityMe Inc</strong>
              <br>
              <i class="fa fa-map-pin fa-fw text-primary"></i> Maharishi Markendeshver Engineering College
              <br>
              <i class="fa fa-phone fa-fw text-primary"></i> 8219984448
              <br>
              <i class="fa fa-envelope-o fa-fw text-primary"></i> info@junity.com
              <br>
            </address>
        </div>



      <a href="#top" class="scrolltop">Top</a>

    </div>
  </footer>

visit/templates/visit/index.html
{% extends 'visit/base.html' %}
{% block content %}

<!DOCTYPE html>
<html lang="en">

<head>
  {%load staticfiles%}
  <meta charset="utf-8">

            <div class="item">
              <div class="row">
                <div class="col-md-6 col-md-push-6 item-caption">
                  <h2 class="h1 text-weight-light">
                      WELCOME
                    </h2>
                  <h4>
                      Reducing Water Footprint
                    </h4>
                  <p>Day-Zero is a situation which arises when the groundwater of a 
                      region runs out and the officials are forced to turn off the water 
                      supply in the city. The Indian city of Bengaluru being designated as
                       the city of Gardens is also following the footsteps of Cape Town and 
                       is going <br>to experience Day-Zero momentarily. According to a report by
                        Niti Aayog, a think-tank <br>department of Indian government for sustainable
                         development around the country, <br>
                         Bangalore as well as 20 other major cities
                          of the country including Delhi, Hyderabad etc. are expected to reach zero
                           groundwater level, affecting the lives of 100 million residents. 
                  </p>
                </div>
                <div class="col-md-6 col-md-pull-6 hidden-xs">
                  <img src="img/slides/slide1.png"  class="center-block img-responsive">
                </div>
              </div>
            </div>
            <!--Slide 2-->
            <div class="item">
              <div class="row">
                <div class="col-md-6 text-right-md item-caption">
                  <h2 class="h1 text-weight-light">
                      <span class="text-primary">E - </span> Water Footprint: 
                    </h2>
                  <h4>
                      Calculate water footprint of your house.
                    </h4>
                  <p>Ideal water local water usage for your houses. </p>
                  <br/>
                  <hr/>

                  <a href="https://bootstrapmade.com" class="btn btn-more btn-lg"><i class="fa fa-plus"></i> Learn More</a>
                </div>
                <div class="col-md-6 hidden-xs">
                  <img src="img/slides/slide2.png"  class="center-block img-responsive">
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- ======== @Region: #content ======== -->
  <div id="content">
    <!-- Mission Statement -->
    <div class="mission text-center block block-pd-sm block-bg-noise">
      <div class="container">
        <h2 class="text-shadow-white">
            We host a special portal dedicated for calculating local E- Water Footprint of the users.
            Jeevan is dedicated to fight Day- Zero by spreading awareness and providing means of reducing 
            depenedency on Ground water Resources. We connect the users who want to actively participate 
            in the campaigns to preserve water to each other.
       </h2>
      </div>
    </div>
    <!--Showcase-->
    <div class="showcase block block-border-bottom-grey">
      <div class="container">
        <h2 class="block-title">
          <!-------
          
         
    <!-- Services -->
    <div class="services block block-bg-gradient block-border-bottom">
      <div class="container">
        <h2 class="block-title">
           <b>

              Our Services

           </b>
          </h2>
        <div class="row">
          <div class="col-md-4 text-center">
            <span class="fa-stack fa-5x">
              <i class="fa fa-circle fa-stack-2x text-primary"></i>
              <i class="fa fa-group fa-stack-1x fa-inverse"></i> </span>
            <h4 class="text-weight-strong">
                Reducing depenedency on Ground Water
              </h4>
            <p>A special portal dedicated on providing the users with alternate sources
              of water and reducing depenedency on ground water Resources. </p>
          </div>
          <div class="col-md-4 text-center">
            <span class="fa-stack fa-5x">
              <i class="fa fa-circle fa-stack-2x text-primary"></i>
              <i class="fa fa-pencil fa-stack-1x fa-inverse"></i> </span>
            <h4 class="text-weight-strong">
                Calculate E-Water Footprint
              </h4>
            <p> We let you calcuate the local water footprint of your house by the means of
              sensors and IOTs and compare them to the idea water usage.
            </p>
            <p>
            </p>
          </div>
          <div class="col-md-4 text-center">
            <span class="fa-stack fa-5x">
              <i class="fa fa-circle fa-stack-2x text-primary"></i>
              <i class="fa fa-cogs fa-stack-1x fa-inverse"></i> </span>
            <h4 class="text-weight-strong">
               Join the movement
              </h4>
            <p>Join Various tree plantation drives with users across the country or start your own by posting
              the details on the form.</p>
            <p>

            </p>
          </div>
        </div>
      </div>
    <!--  
    </div>Background image callout with CSS overlay
Usage: data-block-bg-img="IMAGE-URL" to apply a background image clearly via jQuery .block-bg-overlay = overlays the background image, colour is inherited from block-bg-* classes .block-bg-overlay-NUMBER = determines opcacity value of overlay from 1-9 (default is 5) ie. .block-bg-overlay-2 or .block-bg-overlay-6
-->
    <div class="block block-pd-sm block-bg-grey-dark block-bg-overlay block-bg-overlay-6 text-center" data-block-bg-img="https://picjumbo.imgix.net/HNCK1088.jpg?q=40&amp;w=1650&amp;sharp=30" data-stellar-background-ratio="0.3">
      <h2 class="h-xlg h1 m-a-0">
          <span data-counter-up>6.00</span>s
        </h2>
      <h3 class="h-lg m-t-0 m-b-lg">
          Of Happy Customers!
        </h3>
      <p>
        <a href="#" class="btn btn-more btn-lg i-right">Join them today! <i class="fa fa-angle-right"></i></a>
      </p>
    </div>
    <!--Customer testimonial & Latest Blog posts-->
    <div class="testimonials block-contained">
      <div class="row">
        <!--Customer testimonial-->
        <div class="col-md-6 m-b-lg">
          <h3 class="block-title">
            <b>Our Moto </b>
            </h3>
          <blockquote>
            <p>Be the part of the change you want to see in the world.</p>
            <img src="img/misc/charles-quote.png" alt="Charles Spencer Chaplin">
            <small>
                <strong>Charles Chaplin</strong>
                <br>
                British comic actor
              </small>
          </blockquote>
        </div>
          
  <!-- /content -->
  <!-- Call out block -->
  <div class="block block-pd-sm block-bg-primary">
    <div class="container">
      <div class="row">

        <div class="col-md-8">
          <div class="row">
            <!--Client logos should be within a 120px wide by 60px height image canvas-->
            <div class="col-xs-6 col-md-2">
              <a href="https://bootstrapmade.com" title="Client 1">
                  <img src="img/clients/client1.png" alt="Client 1 logo" class="img-responsive">
                </a>
            </div>
            <div class="col-xs-6 col-md-2">
              <a href="https://bootstrapmade.com" title="Client 2">
                  <img src="img/clients/client2.png" alt="Client 2 logo" class="img-responsive">
                </a>
            </div>
            <div class="col-xs-6 col-md-2">
              <a href="https://bootstrapmade.com" title="Client 3">
                  <img src="img/clients/client3.png" alt="Client 3 logo" class="img-responsive">
                </a>
            </div>
            <div class="col-xs-6 col-md-2">
              <a href="https://bootstrapmade.com" title="Client 4">
                  <img src="img/clients/client4.png" alt="Client 4 logo" class="img-responsive">
                </a>
            </div>
            <div class="col-xs-6 col-md-2">
              <a href="https://bootstrapmade.com" title="Client 5">
                  <img src="img/clients/client5.png" alt="Client 5 logo" class="img-responsive">
                </a>
            </div>
            <div class="col-xs-6 col-md-2">
              <a href="https://bootstrapmade.com" title="Client 6">
                  <img src="img/clients/client6.png" alt="Client 6 logo" class="img-responsive">
                </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- ======== @Region: #footer ======== -->
  <footer id="footer" class="block block-bg-grey-dark" data-block-bg-img="img/bg_footer-map.png" data-stellar-background-ratio="0.4">
    <div class="container">

      <div class="row" id="contact">

        <div class="col-md-3">
          <address>
              <strong>JunityMe Inc</strong>
              <br>
              <i class="fa fa-map-pin fa-fw text-primary"></i> Maharishi Markendeshver Engineering College
              <br>
              <i class="fa fa-phone fa-fw text-primary"></i> 8219984448
              <br>
              <i class="fa fa-envelope-o fa-fw text-primary"></i> info@junity.com
              <br>
            </address>
        </div>



      <a href="#top" class="scrolltop">Top</a>

    </div>
  </footer>

  <!-- Required JavaScript Libraries -->
  <script src="{% static "visit/lib/jquery/jquery.min.js"%}"></script>
  <script src="{% static "visit/lib/bootstrap/js/bootstrap.min.js"%}"></script>
  <script src="{% static "visit/lib/owlcarousel/owl.carousel.min.js"%}"></script>
  <script src="{% static "visit/lib/stellar/stellar.min.js"%}"></script>
  <script src="{% static "visit/lib/waypoints/waypoints.min.js"%}"></script>
  <script src="{% static "visit/lib/counterup/counterup.min.js"%}"></script>
  <script src="{% static "visit/contactform/contactform.js"%}"></script>

  <!-- Template Specisifc Custom Javascript File -->
  <script src="{%static "visit/js/custom.js"%}"></script>

  <!--Custom scripts demo background & colour switcher - OPTIONAL -->
  <script src="{% static "visit/js/color-switcher.js"%}"></script>



</body>

</html>



{% endblock %}

visit/templates/visit/profile.html
This is profile