jeevan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url('^', include('visit.urls')),     #  adding url path for vist application
    url('^', include('main.urls')),     #  adding url path for main application

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.conf.urls import url
from . import views

app_name = 'main'

urlpatterns = [
    url(r'^home/', views.index, name='index'),    # Home page
    url(r'e-market/$', views.emarket, name = 'emarket'),     # rain water 
    url(r'e-market/add-eShop/$', views.AddShop.as_view(), name = 'add-shop'),   # Add an E shop
    url(r'incubators/(?P<incubator_id>[0-9]+)/', views.details, name = 'details'),
    url(r'location/', views.location, name = 'location'),           #  map
    url(r'added/', views.added, name = 'added'),      #your incubator will be added soon page
    url(r'results', views.result, name = 'result'),         # For search function
    url(r'water-footprint/$', views.footprint, name = 'footprint'),
    url(r'underground-water-data/$', views.data, name = 'data'),    # ground water data from ISRO
    url(r'join-movement/$', views.join, name = 'join'),           #for the societies.
    url(r'add-movement/', views.Add.as_view(), name = 'add'),
    url(r'discover/$', views.discover, name = 'discover'),
    url(r'discover/(?P<discover_id>[0-9]+)', views.disc_details, name = 'disc-details'),    # 
    url(r'add-discover/$', views.AddDiscover.as_view(), name = 'add-discover'),
    url(r'contact/$', views.ContactForm.as_view(), name = 'contact-form'),

]

    

visit/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from .views import *
app_name = 'visit'

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'login/', auth_views.LoginView.as_view(), {'template_name': 'visit/registration/login.html'}, name='login'),
    url(r'register/', views.Registration, name='registration'),
    url(r'profile/$', views.Profile, name='profile'),
    url(r'^logout/', views.logoutRequest, name='logout'),
   # url(r'^profiles/new/(?P<pk>\d+)/$', NewUserProfileView.as_view(), name="new-user-profile"),
  #  url(r'^users/(?P<pk>\d+)/edit/', EditUserProfileView.as_view(), name="edit-user-profile"),

]

main/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.urls import reverse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from datetime import date

class Emarket(models.Model):      # These are our database files for the Shop
    name = models.CharField(max_length=30)
    owner = models.CharField(max_length=30)
    city_location = models.CharField(max_length=30)
    description = models.TextField(max_length=100)
    logo = models.FileField()
    verify = models.BooleanField(default = False)
    latt = models.FloatField(default = 30)
    lonn = models.FloatField(default = 25)

    def get_absolute_url(self):
        return reverse('main:added')

    def __str__(self):                  # Displays the following  when a query is made
      return self.name + '-' + self.owner 

class Details(models.Model):
    shop = models.ForeignKey(Emarket, on_delete = models.CASCADE, related_name='banana_pudding')    
    shop_name = models.CharField(max_length = 30)
    shop_img = models.FileField()
    shop_contact = models.CharField(max_length = 600, default = "Enter all means to contact.")
    shop_details = models.TextField(max_length= 2500)
    shop_address = models.TextField(max_length = 600, default = "Address")
    shop_doc = models.FileField()

    def __str__(self):
        return self.shop_name 

class Plantation(models.Model):
    name = models.CharField(max_length = 30)
    city = models.CharField(max_length = 40)
    date = models.CharField(max_length = 40)
    contact = models.CharField(max_length = 40)
    description = models.TextField(max_length= 2500)
 
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main:join')
    

class Join(models.Model):
    name = models.CharField(max_length = 50)
    contact = models.CharField(max_length = 100, default = "Enter phone number.")
    email = models.CharField(max_length = 150)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main:added')

class Discover(models.Model):
    image = models.FileField()
    name = models.CharField(max_length = 30)
    location = models.CharField(max_length = 20)
    description = models.TextField(max_length = 100)


    def __str__(self):
        return self.name

class DiscDetails(models.Model):
    innov = models.ForeignKey(Discover, on_delete = models.CASCADE, related_name='banana_pudding') 
    heading = models.CharField(max_length = 20)
    sub = models.CharField(max_length = 25)   
    passage = models.TextField(max_length = 2500)
    video = models.CharField(max_length = 100)

    def __str__(self):
        return self.heading
    
    def get_absolute_url(self):
        return reverse('main:added')

main/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import *
import numpy as np
import time
import serial
import matplotlib.pyplot as plt
from drawnow import *

def makeFig():
    ax1 = plt.subplot(211)
    plt.ylim(0,50)
    plt.title('Flowrate')
    plt.grid(True)
    plt.ylabel('Flow')
    plt.plot(f, 'ro-', label='litre/min')
    plt.legend(loc='upper left')
    
    


    ax2 = plt.subplot(212, sharex=ax1)
    plt.ylim(0,10000)
    
    plt.grid(True)
    plt.ylabel('volume')
    plt.plot(v, 'ro-', label='mL')
    plt.legend(loc='upper left')

def vol():
    ser = serial.Serial('COM4', baudrate = 9600)
    a = []
    t_end = time.time() + 10 #########
    while time.time() < t_end:
        arduinoData = ser.readline().decode('ascii')
        a.append(arduinoData)
        print(arduinoData)
    #return a[-1]
    for i in range(0,len(a)):
        pos1 = a[i].find(", ")
        #print(pos)
        pos2 = a[i].find("\r")
        a[i] =  a[i][pos1+2:pos2]
    print(a)
    a = [int(i) for i in a]
    return a
        



@login_required
def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect('/login/')
    return render(request, 'main/index.html')

@login_required
def emarket(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect('/login/')
    emarket = Emarket.objects.all().exclude(verify = False)
    pos = Emarket.objects.values_list('latt', 'lonn')
    a = np.array(pos)
    lat1=[]
    long1=[]
    for i in range(len(a)):
        lat1.append(a[i][0])
        long1.append(a[i][1])
    return render(request, 'main/emarket.html', {"emarket": emarket ,'lat' : lat1 , 'lng':long1 })


class AddShop(CreateView):
    model = Emarket
    fields = ['name', 'owner', 'city_location', 'description', 'logo', 'latt', 'lonn']
    template_name = "main/shop_form.html"

def location(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect('/login/')
    em = Emarket.objects.all().exclude(verify = False)
    pos = Emarket.objects.values_list('latt', 'lonn')

    a = np.array(pos)
    lat1=[]
    long1=[]
    for i in range(len(a)):
        lat1.append(a[i][0])
        long1.append(a[i][1])
    return render(request, 'main/location.html', {"em": em ,'lat' : lat1 , 'lng':long1 })

@login_required
def details(request, incubator_id):
    if not request.user.is_authenticated:
        return HttpResponseRedirect('/login/')
    em = get_object_or_404(Emarket, pk = incubator_id)
    details = Details.objects.get(pk = incubator_id)
    return render(request, 'main/details.html', {'em': em, 'details': details})

@login_required
def added(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect('/login/')
    return render(request, 'main/added.html', context = None)

@login_required 
def result(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect('/login/')
    # Shows the matched result
    query = request.GET.get('em_search')
    check = Emarket.objects.filter(name__icontains= query).exclude(verify = False)
    return render(request, 'main/results.html', {'check': check})

@login_required 
def footprint(request):
    v  = vol()
    volume = v
    return render(request, 'main/footprint.html', {'volume': volume})

@login_required 
def data(request):
    return render(request, 'main/data.html', context = None)

@login_required
def join(request):
    drives = Plantation.objects.all()
    return render(request, 'main/join.html', {'drives': drives})

class Add(CreateView):
    model = Plantation
    fields = ['name', 'city', 'date', 'contact', 'description']
    template_name = "main/join_form.html"

def discover(request):
    return render(request, 'main/discover.html', context = None)

def disc_details(request):
    return render(request, 'main/discDetails.html', context = None)


class AddDiscover(CreateView):
    model = Discover
    fields = ['name', 'image', 'location', 'description']
    template_name = "main/addDiscover_form.html"
"""


def disc_details(request, discover_id):
    print(discover_id )
    dis = get_object_or_404(Discover, pk = discover_id)
    det = DiscDetails.objects.get(pk = discover_id)
    
    return render(request, 'main/discDetails.html', {'det': det, 'dis': dis})
"""
class ContactForm(CreateView):
    model = Join
    fields = ['name', 'contact', 'email']
    template_name = "main/contact_form.html"

main/templates/main/addDiscover_form.html
{% extends "main/base.html" %}

{%block content%}
{% load staticfiles %}

<style>
    body
{
margin: 0;
  padding: 0;
    background-image:url({% static 'main/background/img7.jpg' %}), linear-gradient(to bottom, rgba(0,0,0,0.6) 0%,rgba(0,0,0,0.6) 100%);
 background-size: cover;
font-family: sans-serif;
}



.join-link p{
color: #0e028b;
font-family: "Bookman Old Style";

}

.join-link:hover{
text-decoration: underline;

}



.register-text{

color: #2565ff;
}

.register-button{
background-color: #2565ff;
}

.loginBox
{
position: absolute;

top: 80%;
left: 50%;
transform: translate(-50%,-50%);
width: 550px;
padding:  40px;
box-sizing: border-box;
height: 900px;
background: rgba(0,0,0,.6);
font-size: 12px;
}
.user
{
width: 100px;
height: 100px;
border-radius: 50%;
overflow: hidden;
position: absolute;
top: calc(-100px/2);
left: calc(50% - 50px);
}
h2
{
margin: 0;
padding: 0 0 20px;
color: #efed40;
text-align: center;
}
.loginBox p
{
margin: 0;
padding: 0;
font-weight: bold;
color: #fff;
font-size: 20px;
margin-left: 40px;
}
.loginBox input
{
width: 100%;
margin-bottom: 20px;
}
.loginBox input[type="text"],
.loginBox input[type="Password"]
{
border: none;
border-bottom: 1px solid #fff;
outline: none;
height: 40px;
background: transparent;
color: #fff;
font-size: 16px;
font-weight: bold;
}
::placeholder
{
color: rgba(255,255,255,.5);
}
.loginBox input[type="submit"]
{
border: none;
outline: none;
height: 40px;
color: #fff;
font-size: 16px;
background: #2565ff;
cursor: pointer;
border-radius: 20px;
}
.loginBox input[type="submit"]:hover
{
background: #efed40;
color: #262626;
}
.loginBox a
{
color: #fff;
font-size: 14px;
font-weight: bold;
text-decoration: none;
}
</style>
This page is rendered..
<form method="post" novalidate enctype="multipart/form-data" class = "loginBox">
    {% csrf_token %}
        <h2 class = "register-text" style="font-size: 30px;"> Share your Innovation</h2>
        {{ form.as_p }}

    <input class = "register-button" type="submit" name="" value="Add ">

</form>

{% endblock %}

main/templates/main/added.html
{% extends 'main/base.html' %}
{% block content %}

{% load staticfiles %}
<center>	
    <img src="{% static "main/background/tick.png" %}"  style="width: 300px; height: 300px; margin-top: 200px;"> 
</center>
     <p 
     style="text-align: center; font-size: 30px;"> 
Added.
    </p>

{% endblock %}

main/templates/main/base.html
{%load staticfiles%}

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{%block title%} {%endblock%}</title>

  <!-- Bootstrap core CSS -->
  <link href="{%static "main/vendor/bootstrap/css/bootstrap.min.css"%}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{%static "main/css/small-business.css"%}" rel="stylesheet">

</head>

<style>
  body {
      /* The image used */
       background-image: url("{% static "main/background/img7.jpg" %}");
  
      /* Set a specific height */
      height: 100%;
  
      /* Create the parallax scrolling effect */
      background-attachment: fixed;
      background-position: center;
      background-repeat: no-repeat;
      background-size: cover;
  }
  </style>


</style>

<body>

  <!-- Navigation Bar-->

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href='{%url 'main:index'%}'>Jeevan</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive"
        aria-expanded="false " aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href='{%url 'main:index'%}'>Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href='{% url 'main:emarket'%}'>E-Market</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href = '{% url 'main:footprint' %}'>Water Footprint</a>
          </li>&nbsp;&nbsp;
          <li class="nav-item">
            <a class="nav-link" href = '{% url 'main:data' %}'>Ground Water Data</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href = '{% url 'main:join' %}'>Join the Movement</a>  <!-- {% url 'main:join' %}  -->
          </li>
          <li class="nav-item">
              <a class="nav-link" href = '{% url 'main:discover' %}'>Discover</a>       <!-- {% url 'main:discover' %} -->
            </li>
          </li>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    <!-- visit:profile" %} -->
            <a href = "{% url  "#"><li><h2 style="color: antiquewhite;">Welcome, {{ user.get_full_name }}{{ user.username }}!</h2></li></a> 
            <li>   {% if user.is_authenticated %} &nbsp;
        <a href="{% url "visit:logout" %}" style="color: whitesmoke;">logout</a>
      {% else %}
        <a href="{% url 'visit:login' %}">login</a> / <a href="{% url 'visit:registration' %}">signup</a>
      {% endif %}</li>
        </ul>
      </div>
    </div>
  </nav>

  {%block content%}
  {%endblock%}

  <!-- Footer -->

  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  
</body>

main/templates/main/data.html
{% extends 'main/base.html' %}

{% block content %}

_________________________
<iframe height="500px" width="80%" src="https://bhuvan-noeda.nrsc.gov.in/projects/gwis/gwis.php" name="iframe_a"></iframe>
______________
{% endblock %}

main/templates/main/emarket.html
{% load staticfiles %}
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link href = "{% static "main/css/navbar.css"%}" rel = "stylesheet">


<script>
  $(document).ready(function() {
  $('#list').click(function(event){event.preventDefault();$('#products .item').addClass('list-group-item');});
  $('#grid').click(function(event){event.preventDefault();$('#products .item').removeClass('list-group-item');$('#products .item').addClass('grid-group-item');});
});

</script>






<style>
    body{
      /* The image used */
      background-image: url("{% static "main/background/img7.jpg" %}");
  
  /* Set a specific height */
  height: 100%;
   
       /* Create the parallax scrolling effect */
       background-attachment: fixed;
       background-position: center;
       background-repeat: no-repeat;
       background-size: cover;
    }
    
  .map-button{
    border: solid #0a40a4;
    font-weight: bold;
    font-family: sans-serif;
    margin-left: 50%;
    font-size: 26px;
    color: #1c4ca3;
    background: #86a8e7;
    font-color:#093992;
  }
  </style>
  
<!-- Bootstrap core CSS -->
<link href="{%static "main/vendor/bootstrap/css/bootstrap.min.css"%}" rel="stylesheet">

<!-- Custom styles for this template -->
<link href="{%static "main/css/small-business.css"%}" rel="stylesheet">



<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
   <a class="navbar-brand" href='{%url 'main:index'%}' style="font-size:1.8rem;text-decoration: none;text-transform: uppercase;">JEEVAN</a>
    <div class="container">
      
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
            
          <li class="nav-item active">
            <a class="nav-link" href='{%url 'main:index'%}'>Home
              <span class="sr-only">(current)</span> &nbsp;&nbsp;
            </a> 
            
          </li>
          <li class="nav-item">
            <a class="nav-link" href='{% url 'main:emarket'%}'>E-Market</a>
          </li>&nbsp;&nbsp;
          <li class="nav-item">
            <a class="nav-link" href = '{% url 'main:footprint' %}'>Water Footprint</a>
          </li>&nbsp;&nbsp;

          <li class="nav-item">
            <a class="nav-link" href = "{% url "main:location" %}">Locate</a>
          </li> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        
        
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
       
          </li> 
        </ul>
      </div>
    </div>
  </nav>


<form action="/results/" method="GET">
    <div id='container'>  
          <div class='cell'><input type='search' placeholder='Search by Name' name = "em_search"></div>
          <div class='cell'><div class='button' type = "submit" name = "q">Find</div></div>
        </div>
    </form>
  </div>
        <div class="container">
          <div class="well well-sm">
              <strong class="x"style="font-size:1.5rem;">View Type</strong>
              <div class="btn-group" style="border:none;">
                  <a href='{%url 'main:index'%}' id="list" class="btn btn-default btn-sm" style="font-size:2rem;"><span class="glyphicon glyphicon-th-list">
                 </span>List</a> <a href="#" id="grid" class="btn btn-default btn-sm" style="font-size:2rem;"><span
                      class="glyphicon glyphicon-th"></span>Grid</a>
              </div>
          </div>

          
{%for em in emarket%}
    <div id="products" class="something">
            <div class="item  col-xs-4 col-lg-">
                <div class="thumbnail"  style="display:inline-block;width:100%;">
                    <img class="group list-group-image" src="{{em.logo.url}}"   alt="image" />
                    <div class="caption">
                        <h2 class="group inner list-group-item-heading" >
                            {{em.name}}</h2>
                        <h4 class="group inner list-group-item-text">
                            {{em.description}}</h4>
                        <div class="row">
                            <div class="col-xs-12 col-md-6">
                                <p class="lead">
                                  {{em.city_location}}  </p>
                                  </div>
                                  <p><br><br><br><br></p>
                            
                            <div class="col-xs-12 col-md-6">
                                <a class="btn btn-success btn-success-1 detail-link" style="padding: 1rem;border-radius: 10000px;font-size: 20px;display: inline-block;background-color:rgb(74, 96, 218);" href='{%url 'main:details' em.id%}' >Details</a>
                            </div>
                        </div>
              
                    </div>
                </div>
            </div>
    </div>


    {% endfor %}

main/templates/main/join.html
{% load staticfiles %}
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link href = "{% static "main/css/navbar.css"%}" rel = "stylesheet">





<h1 class = 'heading-text' > Join Tree Plantation Drives: </h1>

<style>


    body{
        /* The image used */
        background-image: url("{% static "main/background/img7.jpg" %}");
    
    /* Set a specific height */
    height: 100%;
     
         /* Create the parallax scrolling effect */
         background-attachment: fixed;
         background-position: center;
         background-repeat: no-repeat;
         background-size: cover;
      }
      
    .map-button{
      border: solid #0a40a4;
      font-weight: bold;
      font-family: sans-serif;
      margin-left: 50%;
      font-size: 26px;
      color: #1c4ca3;
      background: #86a8e7;
      font-color:#093992;
    }
    .heading-text{
        font-family: castellar;
        text-align: center;
        background: #5b84d2; 
        margin-left: 450px;
        margin-right: 450px;
        color: #d2e0fa;  
    }

    .conversation-wrap
    {
        box-shadow: -2px 0 3px #ddd;
        padding:0;
        max-height: 400px;
        overflow: auto;
    }
    .conversation
    {
        padding:5px;
        border-bottom:1px solid #ddd;
        margin:0;

    }

    .message-wrap
    {
        box-shadow: 0 0 3px #ddd;
        padding:0;
        align-content: center;
        left: 15%;
        margin-top: 1%;
        background-color: #b6c9ec;
        opacity: 0.7;

    }
    .msg
    {
        padding:5px;
        /*border-bottom:1px solid #ddd;*/
        margin:0;
    }
    .msg-wrap
    {
        padding:10px;
        max-height: 400px;
        overflow: auto;

    }

    .time
    {
        color:#144cb4;

    }

    .send-wrap
    {
        border-top: 1px solid #eee;
        border-bottom: 1px solid #eee;
        padding:10px;
        /*background: #f8f8f8;*/
    }

    
    .highlight
    {
        background-color: #f7f7f9;
        border: 1px solid #e1e1e8;
    }

    .send-message-btn
    {
        border-top-left-radius: 0;
        border-top-right-radius: 0;
        border-bottom-left-radius: 0;

        border-bottom-right-radius: 0;
    }
    .btn-panel
    {
        background: #f7f7f9;
    }

    .btn-panel .btn
    {
        color:#b8b8b8;

        transition: 0.2s all ease-in-out;
    }

    .btn-panel .btn:hover
    {
        color:#666;
        background: #f8f8f8;
    }
    .btn-panel .btn:active
    {
        background: #f8f8f8;
        box-shadow: 0 0 1px #ddd;
    }

    .btn-panel-conversation .btn,.btn-panel-msg .btn
    {

        background: #f8f8f8;
    }
    .btn-panel-conversation .btn:first-child
    {
        border-right: 1px solid #ddd;
    }

    .msg-wrap .media-heading
    {
        color:#003bb3;
        font-weight: 700;
    }


    .msg-date
    {
        background: none;
        text-align: center;
        color:#aaa;
        border:none;
        box-shadow: none;
        border-bottom: 1px solid #ddd;
    }


    body::-webkit-scrollbar {
        width: 12px;
    }
 
    
    /* Let's get this party started */
    ::-webkit-scrollbar {
        width: 6px;
    }

    /* Track */
    ::-webkit-scrollbar-track {
        -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3); 
/*        -webkit-border-radius: 10px;
        border-radius: 10px;*/
    }

    /* Handle */
    ::-webkit-scrollbar-thumb {
/*        -webkit-border-radius: 10px;
        border-radius: 10px;*/
        background:#ddd; 
        -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.5); 
    }
    ::-webkit-scrollbar-thumb:window-inactive {
        background: #ddd; 
    }
  </style>

  <link href="{%static "main/vendor/bootstrap/css/bootstrap.min.css"%}" rel="stylesheet">

  <link href="{%static "main/css/small-business.css"%}" rel="stylesheet">





  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href='{%url 'main:index'%}' style="font-size:1.8rem;text-decoration: none;text-transform: uppercase;">JEEVAN</a>
     <div class="container">
       
       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
       </button>
       <div class="collapse navbar-collapse" id="navbarResponsive">
         <ul class="navbar-nav ml-auto">
             
           <li class="nav-item active">
             <a class="nav-link" href='{%url 'main:index'%}'>Home
               <span class="sr-only">(current)</span> &nbsp;&nbsp;
             </a> 
             
           </li>
         
           <li class="nav-item">
             <a class="nav-link" href="{%url "main:add"%}">Add Plantation Drive</a>
           </li> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
         
         
           &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        
           </li> 
         </ul>
       </div>
     </div>
   </nav>
 








{% for d in drives%}
        <div class="message-wrap col-lg-8">
            <div class="msg-wrap">
                <div class="media msg ">
                    </a>
                    <div class="media-body">
                        <small class="pull-right time"><i class="fa fa-clock-o"></i> {{ d.contact }}</small>
                        <small class="pull-right time"><i class="fa fa-clock-o"></i> <br>Date: {{ d.date }}</small>

                        <a href = '#'>
                          <h3 class="media-heading">{{ d.name }}</h3>
                          <h6 class="media-heading"> {{ d.city }} </h6>
                        </a>
                        <medium class="col-lg-10">
                          {{ d.description }}
                        </medium>
                    </div>
                </div>
                <div class="alert alert-info msg-date">
                   <a href = '{% url "main:contact-form" %}'> <strong>Join</strong> </a>
                </div>
                    </div>
                </div>
{% endfor %}